### ISSUE TITLE
Build Failed?

### ISSUE THREAD

**Issue by jinwk00** [Sticktron/v0rtex-S#10]
> ld: warning: ignoring file /Users/jinwk00/Downloads/v0rtex-S-master/v0rtex-S/libjb.a, missing required architecture x86_64 in file /Users/jinwk00/Downloads/v0rtex-S-master/v0rtex-S/libjb.a (2 slices)
Undefined symbols for architecture x86_64:
  "_grab_hashes", referenced from:
      _trust_files in amfi.o
  "_allkern", referenced from:
      _trust_files in amfi.o
  "_amfitab", referenced from:
      _trust_files in amfi.o
  "_allhash", referenced from:
      _trust_files in amfi.o
  "_numhash", referenced from:
      _trust_files in amfi.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Always getting this whenever I build.

**Comment by Sticktron** [comment]
You can't build it for the Simulator.
