### ISSUE TITLE
iPhone SE 10.3.1 (added custom offsets) doesn't work

### ISSUE THREAD

**Issue by cowpod** [Sticktron/v0rtex-S#4]
Adding iPhone SE offsets leads to a "failed" message and the kernel panicking. Offsets further down.
Additionally, manually finding offsets using radare/hopper yields slightly different results than from the find_offsets.sh (with the last few).

v0rtex offsets for iPhone SE @ 10.3.1, find_offsets.sh:
#define OFFSET_ZONE_MAP                        0xfffffff00754c478
#define OFFSET_KERNEL_MAP                      0xfffffff0075a8050
#define OFFSET_KERNEL_TASK                     0xfffffff0075a8048
#define OFFSET_REALHOST                        0xfffffff00752eba0
#define OFFSET_BZERO                           0xfffffff007081f80
#define OFFSET_BCOPY                           0xfffffff007081dc0
#define OFFSET_COPYIN                          0xfffffff007181218
#define OFFSET_COPYOUT                         0xfffffff00718140c
#define OFFSET_ROOTVNODE                       0xfffffff0075a80b0
#define OFFSET_CHGPROCCNT                      0xfffffff00738e504
#define OFFSET_KAUTH_CRED_REF                  0xfffffff0073688a4
#define OFFSET_IPC_PORT_ALLOC_SPECIAL          0xfffffff007099f7c
#define OFFSET_IPC_KOBJECT_SET                 0xfffffff0070ad1d4
#define OFFSET_IPC_PORT_MAKE_SEND              0xfffffff007099aa0
#define OFFSET_IOSURFACEROOTUSERCLIENT_VTAB    0xfffffff006f25538
#define OFFSET_ROP_ADD_X0_X0_0x10              0xfffffff006525174
#define OFFSET_OSSERIALIZER_SERIALIZE          0xfffffff007441424
#define OFFSET_ROP_LDR_X0_X0_0x10              0xfffffff006474a84

**Comment by Cryptiiiic** [comment]
@cowpod Can you post the logs from xcode.

**Comment by cowpod** [comment]
Sorry! Forgot to update this post. It does work, with custom offsets from the multi-kernel fork of find_offsets.sh.
